services:
  wilma:
    image: fiware/pep-proxy:latest
    container_name: wilma_pep_proxy
    hostname: wilma
    networks:
      - orion_dataspace
    ports:
      - "3003:3003"
    environment:
      - DEBUG=pep-proxy:*

    volumes:
      - "wilma_home:/home"
      - "./config.js:/opt/fiware-pep-proxy/config.js"

networks:
  orion_dataspace:
    external: true

volumes:
  wilma_home: