apiVersion: v1
kind: Secret
metadata:
  name: apisix-admin-secret
  namespace: provider
type: Opaque
stringData:
  admin: "iaB7npvHkpztst7qZ3Mt0JjECXgCcLFw"
  viewer: "iaB7npvHkpztst7qZ3Mt0JjECXgCcLFw"
  admin-key: "iaB7npvHkpztst7qZ3Mt0JjECXgCcLFw"