services:
  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ./apisix_conf/dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - etcd    
    ports:
      - "9000:9000/tcp"
    networks:
      - orion_dataspace

  apisix:
    image: apache/apisix:latest
    container_name: apisix-gateway
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9180:9180"
      - "9092:9092"
      - "9091:9091"
    networks:
      - orion_dataspace

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - "2379:2379/tcp"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      - orion_dataspace

networks:
  orion_dataspace:
    name: orion_dataspace
    external: true

volumes:
  etcd_data: